### ISSUE TITLE
怎么通过WCHISPTool_CMD烧录调试

### ISSUE THREAD

**Issue by vihor3** [ElectronicCats/RISC-V-CH583-CORE#1]
我试图在macOS构建开发、调试和下载固件的环境，但是目前找不到相关资料

**Comment by DeimosHall** [comment]
Hi, unfortunately we're not the main maintainer, this repository is only a mirror. We have used Windows to develop for this platform. We recommend you to install it through bootcamp or virtualize it in case your have an M mac series. If you want to virtualize it I personally recommend you [Parallels](https://www.parallels.com/), it works fine. Another tool you may find useful is https://github.com/ch32-rs/wchisp.
